accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectsListView,
    ProjectsDetailView,
    ProjectsCreateView,
)

urlpatterns = [
    path("", ProjectsListView.as_view(), name="list_projects"),
    path("create/", ProjectsCreateView.as_view(), name="create_project"),
    path("<int:pk>", ProjectsDetailView.as_view(), name="show_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, MyTasksListView, CompleteTaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", MyTasksListView.as_view(), name="show_my_tasks"),
    path(
        "<int:pk>/complete/",
        CompleteTaskUpdateView.as_view(),
        name="complete_task",
    ),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

projects/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="projects"
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField(auto_now_add=False)
    due_date = models.DateTimeField(auto_now_add=False)
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from projects.models import Project


# Create your views here.


class ProjectsListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectsDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectsCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]
    success_url = "/projects/1"

tasks/views.py
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from tasks.models import Task

# Create your views here.


class MyTasksListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/mine.html"
    context_object_name = "tasks"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse("show_project", args=[self.object.project.id])


class CompleteTaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/projects/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Create New Project</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            <h1>Create a new project</h1>
        </header>
        <main>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div>
                        <button>Create</button>
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/projects/detail.html
{% load markdownify %}
<!DOCTYPE html>
<html>
    <head>
        <title>Projects</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div>
            <a href="{% url 'create_task' %}">Create a Task</a>
        </div>
    </header>
    <main>
        <div>
            <h1>{{ project.name }}</h1>
            <p>
                {{ project.description|markdownify }}
            </p>
        </div>
        <div>
            <h2>Tasks</h2>
            {% if project.tasks.all %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    {% for each in project.tasks.all %}
                        <tbody>
                            <tr>
                                <td>{{ each.name }}</td>
                                <td>{{ each.assignee }}</td>
                                <td>{{ each.start_date }}</td>
                                <td>{{ each.due_date }}</td>
                                {% if each.is_completed %}
                                    <td>Yes</td>
                                {% else %}
                                    <td>No</td>
                                {% endif %}
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            {% else %}
                <p>
                    This project has no tasks
                </p>
            {% endif %}
        </div>
    </main>
</body>
</html>

projects/templates/projects/list.html
<!DOCTYPE html>
<html>
    <head>
        <title>Projects</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <nav>
            <a href="{% url 'create_project' %}">Create a new project</a>
        </nav>
        <main>
            <div>
                <h1>My Projects</h1>
                <div>
                    {% if project_list %}
                        <table>
                            <tr>
                                <th>Name</th>
                                <th>Number of tasks</th>
                            </tr>
                            {% for each in project_list %}
                                <tr>
                                    <td>
                                        <a href="{% url 'show_project' each.pk %}">{{ each.name }}</a>
                                    </td>
                                    <td>{{ each.tasks.all|length }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        <p>
                            You are not assigned to any projects
                        </p>
                    {% endif %}
                </div>
            </main>
        </body>
    </html>

tasks/templates/tasks/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Create New Task</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            <h1>Create a new task</h1>
        </header>
        <main>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div>
                        <button>Create</button>
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>

tasks/templates/tasks/mine.html
<!DOCTYPE html>
<html>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>My Tasks</h1>
                <div>
                    {% if tasks %}
                        <table>
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Start date</th>
                                    <th>End date</th>
                                    <th>Is completed</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for each in tasks.all %}
                                    <tr>
                                        <td>{{ each.name }}</td>
                                        <td>{{ each.start_date }}</td>
                                        <td>{{ each.end_date }}</td>
                                        {% if each.is_completed %}
                                            <td>Done</td>
                                        {% else %}
                                            <td>
                                                <form method="post" action="{% url 'complete_task' each.id %}">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="is_completed" value="True">
                                                    <button>Complete</button>
                                                </form>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>
                            You have no tasks
                        </p>
                    {% endif %}
                </div>
            </main>
        </body>
    </html>